services:
  redis-lesan:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    networks:
      - microservices-network

  postgres:
    image: postgres:15
    container_name: postgreSQL_lesan
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./data/pg_data:/var/lib/postgresql/data
    networks:
      - microservices-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Admin UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - microservices-network

  app:
    image: amharic-speech-service-docker-1:latest
    container_name: amharic-speech-service
    ports:
      - "8000:8000"
    networks:
      - microservices-network

  # amharic-speech-service:
  #   build: ./amharic-speech-service
  #   ports:
  #     - "8001:8001"
  #   volumes:
  #     - ./amharic-speech-service:/app
  #   networks:
  #     - microservices-network

  # MinIO storage
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Web console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./uploads:/data
    networks:
      - microservices-network

  # MinIO Client (optional, for admin tasks)
  mc:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (mc alias set local http://minio:9000 minioadmin minioadmin); do sleep 1; done;
      mc mb local/exercises-audio;
      mc mb local/exercises-images;
      mc mb local/user-submissions;
      tail -f /dev/null
      "
    networks:
      - microservices-network

  # envoy:
  #   image: envoyproxy/envoy:v1.29-latest
  #   ports:
  #     - "8080:8080"     # incoming traffic
  #   volumes:
  #     - ./envoy.yaml:/etc/envoy/envoy.yaml
  #   # depends_on:
  #   #   - user-service
  #   #   - ticket-service
  #   networks:
  #     - microservices-network

  # user-service:
  #   build:
  #     context: ./user-service
  #   volumes:
  #     - ./user-service:/app
  #   ports:
  #     - "5080:5080"   # REST
  #     - "5168:5168"   # gRPC
  #   env_file: ./user-service/.env
  #   environment:
  #     - DOTNET_ENVIRONMENT=Development
  #   depends_on:
  #     - redis
  #     - postgres
  #   networks:
  #     - microservices-network
  # gamification-service:
  #   build:
  #     context: ./gamification-service
  #   volumes:
  #     - ./gamification-service:/app
  #   ports:
  #     - "5080:5080"   # REST
  #     - "5168:5168"   # gRPC
  #   env_file: ./gamification-service/.env
  #   depends_on:
  #     - redis
  #     - postgres
  #   networks:
  #     - microservices-network

networks:
  microservices-network:
    driver: bridge